apiVersion: v1
kind: Service
metadata:
  name: hono-service
spec:
  selector:
    app: hono-app
  type: NodePort
  ports:
    - name: http
      port: 3001
      targetPort: 3001
      protocol: TCP
      nodePort: 30081
