apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx-sample
  type: NodePort
  ports:
    - port: 80          # クラスタ内部で公開するポート
      targetPort: 80    # Pod側のコンテナPort
      nodePort: 30080   # Host側(=localhost)に割り当てるポート
