apiVersion: apps/v1
kind: Deployment
metadata:
  name: hono-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hono-app
  template:
    metadata:
      labels:
        app: hono-app
    spec:
      containers:
        - name: hono-container
          image: <YOUR_DOCKER_REPO>/hono-typescript:latest
          # ↑ DockerHubやECRにpushしたイメージを指定する
          ports:
            - containerPort: 3000
