apiVersion: v1
kind: Service
metadata:
  name: hono-service
spec:
  selector:
    app: hono-app
  type: NodePort
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30081  # (例) Nginxが30080なら 30081にする
